---

- name: Create service account for tiller
  k8s:
    definition: "{{ lookup('template', 'service_account.yaml.j2') | from_yaml }}"

- name: Create cluster role for tiller
  k8s:
    definition: "{{ lookup('template', 'role.yaml.j2') | from_yaml }}"

- name: Create cluster role binding for tiller
  k8s:
    definition: "{{ lookup('template', 'role_binding.yaml.j2') | from_yaml }}"

- name: Create deployment for tiller
  k8s:
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"

- name: Create service for tiller
  k8s:
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"
